apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-tiles-pvc
  namespace: arah
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
