services:
  nominatim:
    image: mediagis/nominatim:4.4
    container_name: arah-nominatim
    ports:
      - "7070:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/malaysia-singapore-brunei-updates/
      NOMINATIM_PASSWORD: arah_nominatim
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s

volumes:
  nominatim-data:
